---
##
## webhooks directory
- name: Webhooks directory
  file:
    path: /etc/webhook
    state: directory
    recurse: true

- name: Webhooks logs
  file:
    path: /var/log/webhook
    state: directory
    recurse: true

##
## supervisor config
- name: Supervisor configuration
  copy:
    src: gitlab-webhook.conf
    dest: /etc/supervisor/conf.d

- name: Webhook configuration
  copy:
    src: gitlab.json
    dest: /etc/webhook/gitlab.json
