---
- name: Install Docker Repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker
  yum:
    name: docker
    state: latest

- name: Copy docker daemon.json
  # This allow non root users to use docker
  copy:
      src: templates/daemon.json
      dest: /etc/docker/daemon.json

- name: Start and Enable Docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Adjust hosts
  lineinfile: dest=/etc/sysctl.conf line="net.ipv4.ip_forward=1" state=present

- name: Restart Network
  shell: "service network restart"
